name: Test
on: [pull_request]

jobs:
  test:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            use-cross: false

          - os: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            use-cross: false

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            use-cross: false

          - os: macos-latest
            target: x86_64-apple-darwin
            use-cross: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        target: ${{ matrix.target }}

    - name: Create .cargo/config.toml
      if: ${{ matrix.use-cross == true }}
      shell: bash
      run: |
           mkdir .cargo
           cat > .cargo/config.toml <<EOF
           [target.${{ matrix.target }}]
           rustflags = ["--cfg", "sd_cross_compile"]
           EOF

    - name: Test
      uses: actions-rs/cargo@v1
      with:
        use-cross: ${{ matrix.use-cross }}
        command: test
        args: --target ${{ matrix.target }}
